### PR TITLE
Added new opts `ignore_ft`

### LINKED ISSUE #5: Add ignorance for file type like `NvimTree` and etc.
I am using this plugin and it is great. (recommended by a friend)
I use `aggressive_mode = true` as `grace_period=3` does not work in 3 secs for me atleast.

but if i use `aggressive_mode = true` then i won't get diagnostics in `NvimTree` like plugins.
an opts to ignore certain file types would be a nice addition.
e.g
```lua
ignore_ft = {
	"NvimTree",
}
```

### PR DESCRIPTION
**Pull request by niksingh710**
It is a table of Strings that holds the buffer file type to be ignored Fixes #5

### CODE REVIEW

**Comment by Zeioth** [comment]
This feature was removed in [https://github.com/Zeioth/garbage-day.nvim/releases/tag/v1.0.6](v1.0.6) favor of `excluded_lsp_clients`, which is the same but provides you more control.

**Comment by niksingh710** [comment]
How can I add a filetype in that? Like a normal string will work?

**Comment by niksingh710** [comment]
@Zeioth the documentation only mentions lsp ig.
just add that it also accepts `filetypes` as it is working as expected and this pr irrelevant.

**Comment by Zeioth** [comment]
It is explained in [the manual](https://github.com/Zeioth/garbage-day.nvim?tab=readme-ov-file#available-options). You add the name of a lsp server, and it is ignored.

For example imagine you are in java, and you don't want the java lsp server to be stopped by garbage-day, then you do
```lua
opts = {
  excluded_lsp_clients = { "jdtls" }
}
```

You can add all lsp clients you want like:

```lua
opts = {
  excluded_lsp_clients = { "null-ls", "jdtls" }
}
```

This is handy because by default we exclude `null-ls`,  but users might want a different behavior. 

Play with it.

**Comment by niksingh710** [comment]
I understand the part for `excluded_lsp_clients`

Let's take an e.g. for `lua_ls`
I want it to be managed by `garbage-day` and toggle off and on accordingly, but if I am opening a window like my file explorer that is `NvimTree` then I don't want LSP to be stopped by `garbage-day`.
How can I achieve this behavior by `excluded_lsp_clients`?

**Pull request closed without merging**
